<?php

/**
 * @file
 * Provides administration enhancements, based on Radix theme
 */

/**
 * Implements hook_page_build().
 */
function radix_admin_page_build(&$page) {
  $menu = _radix_admin_get_menu();
  $page['page_bottom']['radix_admin_menu']['#markup'] = theme('radix_admin_menu', array('menu' => $menu));
}

/** 
 * Implements hook_theme().
 */
function radix_admin_theme() {
  return array(
    'radix_admin_menu' => array(
      'variables' => array('menu' => NULL),
      'template' => 'radix-admin-menu',
    ),
  );
}

/**
 * Implements hook_preprocess_html().
 */
function radix_admin_preprocess_html(&$variables) {
  if (radix_admin_admin_menu_enabled()) {
    $variables['classes_array'][] = 'radix-admin-menu';
  }
}

function _radix_admin_get_menu() {
  $menu_tree = menu_tree_all_data('menu-restaurant-admin-menu');
  return menu_tree_output($menu_tree);
}

function radix_admin_admin_menu_enabled() {
  return TRUE;
}